# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout somewhen, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

set $dir /home/uranix/.i3/

# font for window titles. ISO 10646 = Unicode
font -misc-fixed-medium-r-normal--18-120-100-100-C-90-iso10646-1

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+space exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+Q kill

# start dmenu (a program launcher)
bindsym $mod+Return exec dmenu_run

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+H move workspace to output left
bindsym $mod+Shift+J move workspace to output down
bindsym $mod+Shift+K move workspace to output up
bindsym $mod+Shift+L move workspace to output right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+c split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen

# change container layout (stacked, tabbed, default)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout default

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
#bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5: www
bindsym $mod+6 workspace 6: mail
bindsym $mod+7 workspace 7: im
bindsym $mod+8 workspace 8: music
bindsym $mod+9 workspace 9: wine
bindsym $mod+0 workspace 10: video

# move focused container to workspace
bindsym $mod+Shift+exclam move container to workspace 1
bindsym $mod+Shift+at move container to workspace 2
bindsym $mod+Shift+numbersign move container to workspace 3
bindsym $mod+Shift+dollar move container to workspace 4
bindsym $mod+Shift+percent move container to workspace 5: www
bindsym $mod+Shift+asciicircum move container to workspace 6: mail
bindsym $mod+Shift+ampersand move container to workspace 7: im
bindsym $mod+Shift+asterisk move container to workspace 8: music
bindsym $mod+Shift+parenleft move container to workspace 9: wine
bindsym $mod+Shift+parenright move container to workspace 10: video

# reload the configuration file
bindsym $mod+Shift+C reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+R restart
# exit i3
bindsym $mod+Shift+E exec $dir/i3-exit
bindsym XF86PowerOff exec $dir/i3-exit

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode
		# 1000 px ~ 100 ppt

        bindsym j resize shrink width 10 px or 2 ppt
        bindsym k resize grow height 10 px or 2 ppt
        bindsym l resize shrink height 10 px or 2 ppt
        bindsym semicolon resize grow width 10 px or 2 ppt

        bindsym Left  resize shrink width 10 px or 2 ppt
        bindsym Down  resize grow height 10 px or 2 ppt
        bindsym Up    resize shrink height 10 px or 2 ppt
        bindsym Right resize grow width 10 px or 2 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

mode "move" {
        # Move a floating window around 

        bindsym j move left 10 px
        bindsym k move up 10 px
        bindsym l move down 10 px
        bindsym semicolon move right 10 px

        bindsym Left  move left 10 px
        bindsym Up    move up 10 px
        bindsym Down  move down 10 px
        bindsym Right move right 10 px

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"
bindsym $mod+m mode "move"

bindsym $mod+q exec $dir/i3-lock

focus_follows_mouse no

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
		output VGA-0
		position top
		tray_output none
#		font -misc-fixed-medium-r-normal--18-120-100-100-C-90-iso10646-1
		font -xos4-terminus-medium-r-normal--24-*-*-*-*-*-iso10646-1
}

bar {
		output LVDS-0
		position top
        status_command i3status | $dir/i3-exstatus.py
		tray_output LVDS-0
#		font -misc-fixed-medium-r-normal--18-120-100-100-C-90-iso10646-1
		font -xos4-terminus-medium-r-normal--24-*-*-*-*-*-iso10646-1
}

workspace 1 output LVDS-0
workspace 2 output VGA-0
workspace "5: www" output VGA-0
workspace "6: mail" output VGA-0
workspace "7: im" output VGA-0
workspace "8: music" output VGA-0
workspace "9: wine" output LVDS-0
workspace "10: video" output VGA-0

for_window [class="Xfce4-notifyd"] floating enable border 1pixel
for_window [class="I3-exit"] floating enable
for_window [class="etracer"] floating enable
for_window [class="Skype"] floating enable
for_window [class="Iceweasel" title="Downloads"] floating enable

assign [class="Iceweasel"] 5: www
assign [class="Icedove"] 6: mail
assign [class="Qutim"] 7: im
assign [class="Xchat"] 7: im
assign [class="SKype"] 7: im
assign [class="Exaile"] 8: music
assign [class="Wine"] 9: wine
assign [class="Vlc"] 10: video
assign [class="Mplayer"] 10: video

# Terms
exec i3-sensible-terminal
# Daemons
exec --no-startup-id dropbox start
exec /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
exec --no-startup-id nm-applet
# Mailer !!!
exec icedove
# Junk
exec --no-startup-id iceweasel
exec --no-startup-id qutim
exec --no-startup-id exaile

bindsym XF86AudioRaiseVolume exec amixer -q set Master 5+
bindsym XF86AudioLowerVolume exec amixer -q set Master 5-
bindsym XF86AudioMute exec amixer -q sset Master toggle

bindsym XF86MonBrightnessDown exec $dir/backlight_less
bindsym XF86MonBrightnessUp   exec $dir/backlight_more

bindsym XF86Launch1 exec samsung-tools --show-notify --quiet --backlight hotkey
bindsym XF86Launch2 exec samsung-tools --show-notify --quiet --bluetooth hotkey
bindsym XF86Launch3 exec samsung-tools --show-notify --quiet --cpu hotkey
bindsym XF86Display exec samsung-tools --show-notify --quiet --webcam hotkey
bindsym XF86WLAN exec samsung-tools --show-notify --quiet --wireless hotkey
